import React, { useState } from 'react'; // Removed unused 'useEffect'
import { BrowserRouter as Router, Routes, Route, Link, useLocation } from 'react-router-dom';

// --- IMPORTS ---
import GroceryShop from './GroceryShop';
import HospitalFinder from './HospitalFinder';
import DiagnosisInput from './DiagnosisInput';
import ResultsDashboard from './ResultsDashboard'; 
import DietPlans from './DietPlans';           
import DietPlanDetails from './DietPlanDetails'; 
import CartPage from './CartPage';
import Chatbot from './Chatbot'; 
import { LoginPage, SignupPage } from './AuthPages'; 

// --- NAVBAR COMPONENT ---
const Navbar = ({ cartCount, onLogout, user }) => {
  const location = useLocation();
  const showCartButton = location.pathname === '/grocery' || location.pathname === '/cart';

  // Format ID to show cleanly
  const displayId = user?.user_id ? user.user_id.toUpperCase() : "";

  return (
    <nav className="navbar">
      {/* LOGO + ID GROUP */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '15px' }}>
        <div className="nav-logo">NutriCare</div>
        
        {/* User ID Badge */}
        {user && (
          <span style={{ 
            fontSize: '0.85rem', 
            color: '#a0aec0', 
            borderLeft: '1px solid #4a5568', 
            paddingLeft: '15px',
            fontFamily: 'monospace',
            display: 'flex',
            alignItems: 'center',
            gap: '5px'
          }}>
            ID: <span style={{ color: '#63b3ed', fontWeight: 'bold' }}>{displayId}</span>
          </span>
        )}
      </div>

      <div className="nav-links">
        <Link to="/">Home</Link>
        <Link to="/diagnosis">Analyze</Link>
        <Link to="/diet-plans">Diet</Link>
        <Link to="/hospitals">Hospitals</Link>
        <Link to="/grocery">Shop</Link>
      </div>

      <div className="nav-actions">
        {showCartButton && (
          <Link to="/cart" className="btn btn-secondary btn-sm" style={{ marginRight: '10px', display: 'flex', alignItems: 'center' }}>
            🛒 ({cartCount})
          </Link>
        )}
        <button onClick={onLogout} className="btn btn-outline btn-sm">
          Logout ↪
        </button>
      </div>
    </nav>
  );
};

// --- HOME COMPONENT ---
const Home = ({ user }) => (
  <div className="home-container">
    <section className="hero-section">
      <div className="hero-content">
        <span className="hero-badge">AI-Powered Health & Nutrition Platform</span>
        
        {/* Welcome Message */}
        <h1>Welcome, <span className="highlight">{user?.email.split('@')[0]}</span></h1>
        
        <p className="hero-subtitle">
          Transform your health journey with AI-powered disease prediction, personalized diet plans, and smart grocery recommendations.
        </p>
        <div className="hero-buttons">
          <Link to="/diagnosis" className="btn btn-primary">Start Free Analysis →</Link>
          <Link to="/diet-plans" className="btn btn-secondary">Explore Diet Plans</Link>
        </div>
      </div>
    </section>
    
    <section className="features-section">
      <div className="section-header">
        <h2>Everything You Need for Better Health</h2>
        <p>Our comprehensive platform combines AI technology with health expertise to deliver personalized care.</p>
      </div>
      <div className="features-grid">
        <div className="feature-card"><div className="feature-icon">🩺</div><h3>AI Health Analysis</h3><p>Upload your medical reports or describe symptoms for instant AI-powered health insights.</p></div>
        <div className="feature-card"><div className="feature-icon">🥗</div><h3>Personalized Diet Plans</h3><p>Get custom 7-day meal plans generated by AI based on your specific health needs.</p></div>
        <div className="feature-card"><div className="feature-icon">🏥</div><h3>Hospital Recommendations</h3><p>Find nearby specialists and hospitals based on your condition and location.</p></div>
        <div className="feature-card"><div className="feature-icon">🛒</div><h3>Smart Grocery Shopping</h3><p>Filter and shop for groceries that match your dietary requirements.</p></div>
      </div>
    </section>
  </div>
);

// --- MAIN APP COMPONENT ---
function App() {
  // Auth State
  const [user, setUser] = useState(() => {
    const savedUser = localStorage.getItem('nutricare_user');
    return savedUser ? JSON.parse(savedUser) : null;
  });
  
  const [showSignup, setShowSignup] = useState(false);
  const [cart, setCart] = useState([]);
  const [notification, setNotification] = useState(null); 

  const showNotification = (message) => {
    setNotification(message);
    setTimeout(() => {
      setNotification(null);
    }, 3000);
  };

  const handleLogin = (userData) => {
    setUser(userData);
    localStorage.setItem('nutricare_user', JSON.stringify(userData)); 
    showNotification(`👋 Welcome back, ${userData.email}!`);
  };

  const handleLogout = () => {
    setUser(null);
    localStorage.removeItem('nutricare_user'); 
    setCart([]); 
    showNotification("Logged out successfully.");
  };

  const addToCart = (product) => {
    setCart([...cart, product]);
    showNotification(`✅ Added ${product.name} to cart!`);
  };

  const removeFromCart = (indexToRemove) => {
    setCart(cart.filter((_, index) => index !== indexToRemove));
    showNotification("🗑️ Item removed from cart");
  };

  const placeOrder = () => {
    if (cart.length === 0) {
      showNotification("⚠️ Your cart is empty!");
      return;
    }
    setCart([]); 
    showNotification("🎉 Order Placed Successfully! Shipment is on the way.");
  };

  // GATEKEEPER (Login Check)
  if (!user) {
    return (
      <div className="App">
        {notification && (
          <div className="toast-container">
            <div className="toast-message">{notification}</div>
          </div>
        )}

        {showSignup ? (
          <SignupPage onSwitch={() => setShowSignup(false)} />
        ) : (
          <LoginPage onLogin={handleLogin} onSwitch={() => setShowSignup(true)} />
        )}
      </div>
    );
  }

  // MAIN APP ROUTER
  return (
    <Router>
      <div className="App">
        <Navbar cartCount={cart.length} onLogout={handleLogout} user={user} />

        {notification && (
          <div className="toast-container">
            <div className="toast-message">{notification}</div>
          </div>
        )}

        <Chatbot />

        <Routes>
          <Route path="/" element={<Home user={user} />} />
          <Route path="/diagnosis" element={<DiagnosisInput />} />
          <Route path="/results" element={<ResultsDashboard />} />
          <Route path="/hospitals" element={<HospitalFinder />} />
          
          <Route 
            path="/grocery" 
            element={<GroceryShop addToCart={addToCart} />} 
          />
          
          <Route 
            path="/cart" 
            element={
              <CartPage 
                cart={cart} 
                removeFromCart={removeFromCart} 
                onPlaceOrder={placeOrder} 
              />
            } 
          />
          
          <Route path="/diet-plans" element={<DietPlans />} />
          <Route path="/diet-plans/:type" element={<DietPlanDetails />} />
        </Routes>

        <footer className="footer">
          <div className="footer-content">
            <div className="footer-col"><h3>NutriCare</h3><p>AI-powered personalized diet planning for better health outcomes.</p></div>
            <div className="footer-col"><h4>Features</h4><ul><li>Health Analysis</li><li>Diet Plans</li><li>Find Hospitals</li><li>Grocery Shopping</li></ul></div>
            <div className="footer-col"><h4>Company</h4><ul><li>About Us</li><li>Blog</li><li>Careers</li><li>Contact</li></ul></div>
            <div className="footer-col"><h4>Legal</h4><ul><li>Privacy Policy</li><li>Terms of Service</li><li>HIPAA Compliance</li></ul></div>
          </div>
          <div className="footer-bottom">© 2025 NutriCare. All rights reserved.</div>
        </footer>
      </div>
    </Router>
  );
}

export default App;